#!/usr/bin/env bash
# install.sh — set up exp-runner on this machine for a teammate.
#
#   git clone <repo> && cd exp-runner && ./install.sh
#
# What it does (idempotent):
#   1. checks prerequisites (git, python3 >= 3.9; warns if codex/claude are missing
#      since you must be logged into one of them to actually run jobs);
#   2. makes the Python deps (PyYAML, jsonschema) importable — using whatever the
#      machine already has, else `pip install --user`, else a private .runner-venv;
#   3. drops an `exp-runner` command on your PATH (a thin wrapper around run.sh).
#
# Env overrides:
#   BINDIR=/somewhere/bin   where to put the `exp-runner` wrapper (default ~/.local/bin)
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BINDIR="${BINDIR:-$HOME/.local/bin}"
VENV="$HERE/.runner-venv"

ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*" >&2; }
die()  { printf '  \033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

echo "exp-runner installer  ($HERE)"
echo ""

# ── 1. Prerequisites ─────────────────────────────────────────────────────────
echo "Checking prerequisites…"
command -v git >/dev/null     || die "git not found — install git first."
command -v python3 >/dev/null || die "python3 not found — install Python 3.9+ first."
ok "git: $(git --version | awk '{print $3}')"

PYV=$(python3 -c 'import sys;print("%d.%d"%sys.version_info[:2])')
python3 -c 'import sys;sys.exit(0 if sys.version_info>=(3,9) else 1)' \
  || die "python3 is $PYV; exp-runner needs >= 3.9."
ok "python3: $PYV"

# Agent CLIs are needed at RUN time (you log in separately). Warn, don't fail.
HAVE_AGENT=0
command -v codex  >/dev/null && { ok "codex CLI found";  HAVE_AGENT=1; }
command -v claude >/dev/null && { ok "claude CLI found"; HAVE_AGENT=1; }
if [[ "$HAVE_AGENT" == 0 ]]; then
  warn "neither 'codex' nor 'claude' is on PATH."
  warn "install at least one and log in before running jobs:"
  warn "    codex login        # https://developers.openai.com/codex"
  warn "    claude login       # https://docs.claude.com/claude-code"
fi

# ── 2. Python dependencies (PyYAML, jsonschema) ──────────────────────────────
echo ""
echo "Ensuring Python deps (PyYAML, jsonschema, matplotlib, numpy)…"
DEPS_CHECK='import yaml, jsonschema, matplotlib, numpy'
WRAP_PATH_LINE=""   # set if we fall back to a private venv
if python3 -c "$DEPS_CHECK" 2>/dev/null; then
  ok "already importable by python3"
elif python3 -m pip install --user -q -r "$HERE/requirements.txt" 2>/dev/null \
     && python3 -c "$DEPS_CHECK" 2>/dev/null; then
  ok "installed with pip --user"
else
  warn "couldn't install into the system/user python (PEP 668?) — using a private venv"
  python3 -m venv "$VENV"
  "$VENV/bin/pip" install -q --upgrade pip
  "$VENV/bin/pip" install -q -r "$HERE/requirements.txt"
  "$VENV/bin/python" -c "$DEPS_CHECK" || die "venv deps failed to import"
  WRAP_PATH_LINE="export PATH=\"$VENV/bin:\$PATH\"   # exp-runner's private deps"
  ok "built $VENV"
fi

# ── 3. Put `exp-runner` on PATH ──────────────────────────────────────────────
echo ""
echo "Installing the exp-runner command into $BINDIR…"
mkdir -p "$BINDIR"
WRAPPER="$BINDIR/exp-runner"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# exp-runner — installed wrapper (generated by install.sh). Runs the real entry
# point with an absolute path so it works from any directory. Jobs are written
# under the cloned repo at $HERE/jobs/.
$WRAP_PATH_LINE
exec "$HERE/run.sh" "\$@"
EOF
chmod +x "$WRAPPER"
ok "wrote $WRAPPER"

echo ""
if [[ ":$PATH:" == *":$BINDIR:"* ]]; then
  ok "$BINDIR is on your PATH — you're ready."
  echo ""
  echo "Try:  exp-runner            # interactive wizard"
  echo "      exp-runner --help"
else
  warn "$BINDIR is NOT on your PATH. Add this to your shell rc, then restart your shell:"
  echo ""
  echo "      export PATH=\"$BINDIR:\$PATH\""
  echo ""
  echo "Until then, run it directly:  $HERE/run.sh"
fi
echo ""
echo "Prerequisite reminder: log in to your agent CLI before running jobs (codex login / claude login)."
