#!/usr/bin/env python3
"""
make_tasks_file.py — assemble tasks/tasks.yaml from the per-task packs.

RESPONSIBILITY
  `jobspec.py create --tasks-file` wants a list of `{id, task, accept}` with the
  prompt text INLINE, but a task pack keeps that text in `task.md` and
  `accept.md` next to the patches and the fact it belongs to. This module is the
  one-way bridge: it reads every `tasks/<task_id>/` directory that carries both
  files and emits the flat list.

  Regenerating is the point. `tasks.yaml` is a derived artifact and editing it by
  hand puts the prompt the agent sees out of step with the pack the detector was
  verified against — which is unrecoverable after the run, because nothing
  downstream records which of the two was authoritative.

INPUTS
  tasks/<task_id>/task.md    the task handed to the agent
  tasks/<task_id>/accept.md  the acceptance description handed to the judge
  A directory is skipped, loudly, when either file is missing.

OUTPUTS
  YAML on stdout (a list of `{id, task, accept}`, prompt text in literal block
  scalars), or to --out. Diagnostics go to stderr, so the payload can be piped.
  Emitted without PyYAML on purpose: the system python3 has neither `yaml` nor
  `jsonschema` until install.sh has run, and this has to work before then.

CLI
  python3 tasks/make_tasks_file.py [--tasks-dir DIR] [--out PATH] [--check]
    --check  compare against --out (default tasks/tasks.yaml) and exit 1 on drift
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Sequence

HERE = Path(__file__).resolve().parent
DEFAULT_OUT = HERE / "tasks.yaml"

TASK_FILE = "task.md"
ACCEPT_FILE = "accept.md"
PACK_FILE = "fact_pack.yaml"
CRITERIA_FILE = "criteria.json"
#: Known-correct solutions. `ref_without_mandate` is an INDEPENDENT implementation of
#: the same behaviour, which is why two are used: one reference can be accidentally
#: matched by a criterion that only fits that implementation.
REFERENCE_GLOB = "ref_*.patch"

HEADER = ("# GENERATED by tasks/make_tasks_file.py — do not edit.\n"
    "#\n"
    "# The flat {id, task, accept} list `jobspec.py create --tasks-file` reads.\n"
    "# The authoritative text lives in tasks/<task_id>/{task,accept}.md, beside\n"
    "# the fact pack whose detector was verified against it.\n"
    )


def block_scalar(text: str, indent: str = "    ") -> str:
    """Render `text` as a YAML literal block scalar body.

    `|-` strips the trailing newline, which keeps the round trip exact for text
    that already ends in one. A blank line is emitted with no indentation at all:
    trailing whitespace inside a block scalar is preserved by YAML, and a line of
    spaces in a task prompt is the kind of difference that shows up as a hash
    mismatch three components downstream.
    """
    lines = text.rstrip("\n").split("\n")
    return "\n".join(f"{indent}{line}".rstrip() for line in lines)


def discover(tasks_dir: Path) -> list[Path]:
    """Every task-pack directory, in sorted order."""
    return sorted(d for d in tasks_dir.iterdir() if d.is_dir() and (d / TASK_FILE).is_file()
    )


def render(tasks_dir: Path) -> tuple[str, list[str]]:
    """Build the YAML document. Returns (text, problems)."""
    problems: list[str] = []
    chunks: list[str] = [HEADER]
    found = 0
    for pack in discover(tasks_dir):
        task_path = pack / TASK_FILE
        accept_path = pack / ACCEPT_FILE
        if not accept_path.is_file():
            problems.append(f"{pack.name}: has {TASK_FILE} but no {ACCEPT_FILE}; skipped")
            continue
        if not (pack / PACK_FILE).is_file():
            problems.append(f"{pack.name}: no {PACK_FILE} — the task has no fact bound to it")
        task = task_path.read_text(encoding="utf-8")
        accept = accept_path.read_text(encoding="utf-8")
        if not task.strip() or not accept.strip():
            problems.append(f"{pack.name}: {TASK_FILE} or {ACCEPT_FILE} is empty; skipped")
            continue
        chunk = (f"- id: {pack.name}\n"
            f"  task: |-\n{block_scalar(task)}\n"
            f"  accept: |-\n{block_scalar(accept)}\n"
    )
        # The FROZEN battery and the known-correct solutions, emitted as paths relative
        # to the repo root (judge.py resolves them against the job dir, then here).
        # Without criteria_file every job authors its OWN battery from one unseeded LLM
        # call, and two such jobs are not comparable to each other; without
        # reference_patches the floor check only ever proves "fails before" and assumes
        # "passes after", which is how a criterion broken behind a short-circuit ships
        # as discriminating. Both files are in the pack; emitting them is what wires
        # them up.
        rel = f"tasks/{pack.name}"
        if (pack / CRITERIA_FILE).is_file():
            chunk += f"  criteria_file: {rel}/{CRITERIA_FILE}\n"
        else:
            problems.append(f"{pack.name}: no {CRITERIA_FILE} — every job will synthesize its own "
                f"battery and they will not be comparable")
        refs = [p.name for p in sorted(pack.glob(REFERENCE_GLOB))]
        if refs:
            chunk += "  reference_patches:\n"
            chunk += "".join(f"    - {rel}/{name}\n" for name in refs)
        else:
            problems.append(f"{pack.name}: no {REFERENCE_GLOB} — the floor check stays ONE-SIDED")
        chunks.append(chunk)
        found += 1
    if not found:
        problems.append(f"no task packs found under {tasks_dir}")
    return "\n".join(chunks), problems


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="assemble tasks.yaml from the task packs")
    parser.add_argument("--tasks-dir", default=str(HERE))
    parser.add_argument("--out", help=f"write here (default {DEFAULT_OUT} when --check)")
    parser.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = parser.parse_args(argv)

    tasks_dir = Path(args.tasks_dir).resolve()
    if not tasks_dir.is_dir():
        print(f"no such directory: {tasks_dir}", file=sys.stderr)
        return 2

    text, problems = render(tasks_dir)
    for problem in problems:
        print(f"[make-tasks-file] {problem}", file=sys.stderr)

    if args.check:
        target = Path(args.out) if args.out else DEFAULT_OUT
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if current == text:
            print(f"[make-tasks-file] {target} is up to date", file=sys.stderr)
            return 1 if problems else 0
        print(f"[make-tasks-file] STALE: {target} differs from the packs", file=sys.stderr)
        return 1

    if args.out:
        Path(args.out).write_text(text, encoding="utf-8")
        print(f"[make-tasks-file] wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 1 if any("skipped" in p or "no task packs" in p for p in problems) else 0


if __name__ == "__main__":
    raise SystemExit(main())
